# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.x
    - name: Restore dependencies
      run: dotnet restore src/ChirpWeb/ChirpWeb.csproj
      
    - name: Build web
      run: dotnet build src/ChirpWeb/ChirpWeb.csproj --no-restore


  unit_test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
          
      - name: Restore dependencies for Unit Tests
        run: dotnet restore UnitTest/UnitTest.csproj
        
      - name: Run Unit Tests
        env:
          AUTHENTICATION_GITHUB_CLIENTID: ${{ secrets.AUTHENTICATION_GITHUB_CLIENTID }}
          AUTHENTICATION_GITHUB_CLIENTSECRET: ${{ secrets.AUTHENTICATION_GITHUB_CLIENTSECRET }}
        run: dotnet test UnitTest/UnitTest.csproj --verbosity normal
        
  integration_test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
          
      - name: Restore dependencies for Integration Tests
        run: dotnet restore IntegrationTest/IntegrationTest.csproj
        
      - name: Run Integration Tests
        env:
          AUTHENTICATION_GITHUB_CLIENTID: ${{ secrets.AUTHENTICATION_GITHUB_CLIENTID }}
          AUTHENTICATION_GITHUB_CLIENTSECRET: ${{ secrets.AUTHENTICATION_GITHUB_CLIENTSECRET }}
        run: dotnet test IntegrationTest/IntegrationTest.csproj --verbosity normal
        
  e2e_test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies for End To End Tests
        run: |
          dotnet restore test/Chirp.TestE2E/Chirp.TestE2E.csproj

      - name: Build End To End Tests
        run: dotnet build PlaywrightTests/PlaywrightTests.csproj --no-restore

      - name: Run Web Application
        run: dotnet run --project src/ChirpWeb/ChirpWeb.csproj --urls "http://localhost:5273" &
        env:
          AUTHENTICATION_GITHUB_CLIENTID: ${{ secrets.AUTHENTICATION_GITHUB_CLIENTID }}
          AUTHENTICATION_GITHUB_CLIENTSECRET: ${{ secrets.AUTHENTICATION_GITHUB_CLIENTSECRET }}

      - name: Wait for Web Application to Start
        run: sleep 10

      - name: Install Playwright
        run: pwsh PlaywrightTests/bin/Debug/net8.0/playwright.ps1 install

      - name: End To End Test
        env:
          AUTHENTICATION_GITHUB_CLIENTID: ${{ secrets.AUTHENTICATION_GITHUB_CLIENTID }}
          AUTHENTICATION_GITHUB_CLIENTSECRET: ${{ secrets.AUTHENTICATION_GITHUB_CLIENTSECRET }}
          #GITHUBTESTACCOUNTUSERNAME: ${{ secrets.GITHUBTESTACCOUNTUSERNAME }}
          #GITHUBTESTACCOUNTPASSWORD: ${{ secrets.GITHUBTESTACCOUNTPASSWORD }}
        run: |
          dotnet test PlaywrightTests/PlaywrightTests.csproj --verbosity normal
