#Code donated by group 15
name: Build, Test and Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
  
  
    - name: Setup
      uses: actions/setup-dotnet@v4
      with:
          dotnet-version: 8.x

    - name: Build Linux
      shell: bash
      run: |
          # Define some variables for things we need
          tag=$(git describe --tags --abbrev=0)
          release_name="App-$tag-linux-x64"

          # Build everything
          dotnet publish src/ChirpWeb/ChirpWeb.csproj --framework net8.0 --runtime linux-x64 -c Release -o "Linux-release" -p:PublishSingleFile=true
          
          7z a -tzip "Chirp-Linux-release.zip" "Linux-release"

          rm -r Linux-release

    - name: Build MacOS
      shell: bash
      run: |
          # Define some variables for things we need
          tag=$(git describe --tags --abbrev=0)
          release_name="App-$tag-osx-x64"

          # Build everything
          dotnet publish src/ChirpWeb/ChirpWeb.csproj --framework net8.0 --runtime osx-x64 -c Release -o "MacOS-release" -p:PublishSingleFile=true
          
          7z a -tzip "Chirp-MacOS-release.zip" "MacOS-release"

          rm -r MacOS-release


    - name: Build Windows
      shell: bash
      run: |
          # Define some variables for things we need
          tag=$(git describe --tags --abbrev=0)
          release_name="App-$tag-win-x64"

          # Build everything
          dotnet publish src/ChirpWeb/ChirpWeb.csproj --framework net8.0 --runtime win-x64 -c Release -o "Windows-release" -p:PublishSingleFile=true
          
          7z a -tzip "Chirp-Windows-release.zip" "./Windows-release/*"

          rm -r Windows-release

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
          files: |
           Chirp-Linux-release.zip
           Chirp-MacOS-release.zip
           Chirp-Windows-release.zip
            
          repo-token: ${{ secrets.GITHUB_TOKEN }}
